import type { AccountLike } from "@/lib/domain";

// Illustrative-only roster used on the marketing home page to demonstrate
// the Hive Composition mechanism before signup. Not real player data.
export const DEMO_ROSTER: AccountLike[] = [
  {
    gameId: BigInt(1),
    name: "Ironclad",
    keep: 45,
    power: 69,
    rally: 78000000,
    rein: 0,

    atkGroundAttack: 58,
    atkGroundHp: 43,
    atkGroundDefense: 43,
    atkRangedAttack: 74,
    atkRangedHp: 55,
    atkRangedDefense: 55,
    atkCavalryAttack: 64,
    atkCavalryHp: 48,
    atkCavalryDefense: 48,
    atkSiegeAttack: 61,
    atkSiegeHp: 46,
    atkSiegeDefense: 45,

    defGroundAttack: 15,
    defGroundHp: 11,
    defGroundDefense: 12,
    defRangedAttack: 14,
    defRangedHp: 11,
    defRangedDefense: 10,
    defCavalryAttack: 17,
    defCavalryHp: 13,
    defCavalryDefense: 12,
    defSiegeAttack: 16,
    defSiegeHp: 12,
    defSiegeDefense: 12,

    defGroundDebuffAttack: 5,
    defGroundDebuffHp: 4,
    defGroundDebuffDefense: 3,
    defRangedDebuffAttack: 4,
    defRangedDebuffHp: 3,
    defRangedDebuffDefense: 2,
    defCavalryDebuffAttack: 5,
    defCavalryDebuffHp: 4,
    defCavalryDebuffDefense: 4,
    defSiegeDebuffAttack: 8,
    defSiegeDebuffHp: 6,
    defSiegeDebuffDefense: 6,
  },
  {
    gameId: BigInt(2),
    name: "Vantage",
    keep: 45,
    power: 55,
    rally: 0,
    rein: 0,

    atkGroundAttack: 53,
    atkGroundHp: 40,
    atkGroundDefense: 40,
    atkRangedAttack: 60,
    atkRangedHp: 45,
    atkRangedDefense: 45,
    atkCavalryAttack: 56,
    atkCavalryHp: 42,
    atkCavalryDefense: 41,
    atkSiegeAttack: 55,
    atkSiegeHp: 41,
    atkSiegeDefense: 42,

    defGroundAttack: 7,
    defGroundHp: 5,
    defGroundDefense: 6,
    defRangedAttack: 6,
    defRangedHp: 5,
    defRangedDefense: 5,
    defCavalryAttack: 9,
    defCavalryHp: 7,
    defCavalryDefense: 6,
    defSiegeAttack: 8,
    defSiegeHp: 6,
    defSiegeDefense: 6,

    defGroundDebuffAttack: 2,
    defGroundDebuffHp: 2,
    defGroundDebuffDefense: 2,
    defRangedDebuffAttack: 2,
    defRangedDebuffHp: 2,
    defRangedDebuffDefense: 1,
    defCavalryDebuffAttack: 2,
    defCavalryDebuffHp: 2,
    defCavalryDebuffDefense: 2,
    defSiegeDebuffAttack: 3,
    defSiegeDebuffHp: 2,
    defSiegeDebuffDefense: 3,
  },
  {
    gameId: BigInt(3),
    name: "Rampart",
    keep: 44,
    power: 51,
    rally: 0,
    rein: 121000000,

    atkGroundAttack: 46,
    atkGroundHp: 34,
    atkGroundDefense: 34,
    atkRangedAttack: 50,
    atkRangedHp: 38,
    atkRangedDefense: 38,
    atkCavalryAttack: 50,
    atkCavalryHp: 38,
    atkCavalryDefense: 37,
    atkSiegeAttack: 50,
    atkSiegeHp: 37,
    atkSiegeDefense: 37,

    defGroundAttack: 24,
    defGroundHp: 18,
    defGroundDefense: 18,
    defRangedAttack: 19,
    defRangedHp: 14,
    defRangedDefense: 15,
    defCavalryAttack: 20,
    defCavalryHp: 15,
    defCavalryDefense: 15,
    defSiegeAttack: 22,
    defSiegeHp: 17,
    defSiegeDefense: 16,

    defGroundDebuffAttack: 7,
    defGroundDebuffHp: 5,
    defGroundDebuffDefense: 6,
    defRangedDebuffAttack: 6,
    defRangedDebuffHp: 4,
    defRangedDebuffDefense: 4,
    defCavalryDebuffAttack: 8,
    defCavalryDebuffHp: 6,
    defCavalryDebuffDefense: 5,
    defSiegeDebuffAttack: 11,
    defSiegeDebuffHp: 8,
    defSiegeDebuffDefense: 9,
  },
  {
    gameId: BigInt(4),
    name: "Nightfall",
    keep: 44,
    power: 33,
    rally: 0,
    rein: 61000000,

    atkGroundAttack: 42,
    atkGroundHp: 31,
    atkGroundDefense: 31,
    atkRangedAttack: 46,
    atkRangedHp: 34,
    atkRangedDefense: 34,
    atkCavalryAttack: 44,
    atkCavalryHp: 33,
    atkCavalryDefense: 33,
    atkSiegeAttack: 42,
    atkSiegeHp: 32,
    atkSiegeDefense: 32,

    defGroundAttack: 6,
    defGroundHp: 5,
    defGroundDefense: 5,
    defRangedAttack: 6,
    defRangedHp: 4,
    defRangedDefense: 4,
    defCavalryAttack: 8,
    defCavalryHp: 6,
    defCavalryDefense: 6,
    defSiegeAttack: 7,
    defSiegeHp: 5,
    defSiegeDefense: 6,

    defGroundDebuffAttack: 2,
    defGroundDebuffHp: 2,
    defGroundDebuffDefense: 1,
    defRangedDebuffAttack: 2,
    defRangedDebuffHp: 1,
    defRangedDebuffDefense: 1,
    defCavalryDebuffAttack: 2,
    defCavalryDebuffHp: 2,
    defCavalryDebuffDefense: 1,
    defSiegeDebuffAttack: 3,
    defSiegeDebuffHp: 2,
    defSiegeDebuffDefense: 2,
  },
  {
    gameId: BigInt(5),
    name: "Bastion",
    keep: 43,
    power: 30,
    rally: 0,
    rein: 83870000,

    atkGroundAttack: 44,
    atkGroundHp: 33,
    atkGroundDefense: 33,
    atkRangedAttack: 54,
    atkRangedHp: 41,
    atkRangedDefense: 40,
    atkCavalryAttack: 48,
    atkCavalryHp: 36,
    atkCavalryDefense: 36,
    atkSiegeAttack: 51,
    atkSiegeHp: 38,
    atkSiegeDefense: 39,

    defGroundAttack: 11,
    defGroundHp: 8,
    defGroundDefense: 9,
    defRangedAttack: 9,
    defRangedHp: 7,
    defRangedDefense: 6,
    defCavalryAttack: 10,
    defCavalryHp: 7,
    defCavalryDefense: 7,
    defSiegeAttack: 10,
    defSiegeHp: 8,
    defSiegeDefense: 7,

    defGroundDebuffAttack: 3,
    defGroundDebuffHp: 2,
    defGroundDebuffDefense: 3,
    defRangedDebuffAttack: 2,
    defRangedDebuffHp: 2,
    defRangedDebuffDefense: 2,
    defCavalryDebuffAttack: 3,
    defCavalryDebuffHp: 2,
    defCavalryDebuffDefense: 3,
    defSiegeDebuffAttack: 5,
    defSiegeDebuffHp: 4,
    defSiegeDebuffDefense: 3,
  },
  {
    gameId: BigInt(6),
    name: "Wraith",
    keep: 43,
    power: 26,
    rally: 0,
    rein: 0,

    atkGroundAttack: 34,
    atkGroundHp: 25,
    atkGroundDefense: 25,
    atkRangedAttack: 41,
    atkRangedHp: 31,
    atkRangedDefense: 31,
    atkCavalryAttack: 36,
    atkCavalryHp: 27,
    atkCavalryDefense: 28,
    atkSiegeAttack: 36,
    atkSiegeHp: 27,
    atkSiegeDefense: 28,

    defGroundAttack: 4,
    defGroundHp: 3,
    defGroundDefense: 3,
    defRangedAttack: 4,
    defRangedHp: 3,
    defRangedDefense: 2,
    defCavalryAttack: 6,
    defCavalryHp: 4,
    defCavalryDefense: 4,
    defSiegeAttack: 5,
    defSiegeHp: 4,
    defSiegeDefense: 3,

    defGroundDebuffAttack: 1,
    defGroundDebuffHp: 1,
    defGroundDebuffDefense: 1,
    defRangedDebuffAttack: 1,
    defRangedDebuffHp: 1,
    defRangedDebuffDefense: 0,
    defCavalryDebuffAttack: 1,
    defCavalryDebuffHp: 1,
    defCavalryDebuffDefense: 1,
    defSiegeDebuffAttack: 2,
    defSiegeDebuffHp: 2,
    defSiegeDebuffDefense: 1,
  },
  {
    gameId: BigInt(7),
    name: "Sentinel",
    keep: 42,
    power: 20,
    rally: 24500000,
    rein: 26100000,

    atkGroundAttack: 21,
    atkGroundHp: 16,
    atkGroundDefense: 15,
    atkRangedAttack: 30,
    atkRangedHp: 23,
    atkRangedDefense: 23,
    atkCavalryAttack: 30,
    atkCavalryHp: 22,
    atkCavalryDefense: 22,
    atkSiegeAttack: 26,
    atkSiegeHp: 20,
    atkSiegeDefense: 19,

    defGroundAttack: 7,
    defGroundHp: 5,
    defGroundDefense: 5,
    defRangedAttack: 5,
    defRangedHp: 4,
    defRangedDefense: 3,
    defCavalryAttack: 5,
    defCavalryHp: 4,
    defCavalryDefense: 4,
    defSiegeAttack: 6,
    defSiegeHp: 5,
    defSiegeDefense: 4,

    defGroundDebuffAttack: 2,
    defGroundDebuffHp: 1,
    defGroundDebuffDefense: 1,
    defRangedDebuffAttack: 1,
    defRangedDebuffHp: 1,
    defRangedDebuffDefense: 1,
    defCavalryDebuffAttack: 2,
    defCavalryDebuffHp: 1,
    defCavalryDebuffDefense: 1,
    defSiegeDebuffAttack: 2,
    defSiegeDebuffHp: 2,
    defSiegeDebuffDefense: 2,
  },
  {
    gameId: BigInt(8),
    name: "Falcon",
    keep: 42,
    power: 16,
    rally: 0,
    rein: 0,

    atkGroundAttack: 19,
    atkGroundHp: 14,
    atkGroundDefense: 15,
    atkRangedAttack: 24,
    atkRangedHp: 18,
    atkRangedDefense: 18,
    atkCavalryAttack: 20,
    atkCavalryHp: 15,
    atkCavalryDefense: 16,
    atkSiegeAttack: 18,
    atkSiegeHp: 14,
    atkSiegeDefense: 14,

    defGroundAttack: 3,
    defGroundHp: 2,
    defGroundDefense: 2,
    defRangedAttack: 2,
    defRangedHp: 2,
    defRangedDefense: 2,
    defCavalryAttack: 4,
    defCavalryHp: 3,
    defCavalryDefense: 2,
    defSiegeAttack: 3,
    defSiegeHp: 2,
    defSiegeDefense: 3,

    defGroundDebuffAttack: 1,
    defGroundDebuffHp: 1,
    defGroundDebuffDefense: 0,
    defRangedDebuffAttack: 1,
    defRangedDebuffHp: 1,
    defRangedDebuffDefense: 0,
    defCavalryDebuffAttack: 1,
    defCavalryDebuffHp: 1,
    defCavalryDebuffDefense: 0,
    defSiegeDebuffAttack: 1,
    defSiegeDebuffHp: 1,
    defSiegeDebuffDefense: 1,
  },
];
